#!/bin/bash
set -euo pipefail

echo "setting envs"
export USER="JohnDoe"
export PASSWORD="Welcome@123"

echo "--- Searching for Clowns 🤡 $USER"
echo "$BUILDKITE_BUILD_CHECKOUT_PATH"
echo "print user ${USER}"

if grep -inr -C1 "🤡" . ; then
  echo "^^^ +++"
  echo "+++ :warning: Detected clowns! 🔪 Username: ${USER}"
  echo "Print username with escaping? $$USER"
  echo "Print without? $USER"
  exit 1
fi
